### ISSUE TITLE
Difference between gameDir and contentUrl?

### ISSUE THREAD

**Issue by SomeRandomDude870** [proconsule/nspindexer#6]
As the title says.
What do I have to fill into the Variables?

Mine looks like:
$gameDir = "H:\Switch Games"; /* Absolute Files Path, no trailing slash */
$contentUrl = "\Switch Games"; /* Files URL, no trailing slash */

but when I go to the page I don´t get any games loaded.
How is the path supposed to look like?

**Comment by jangrewe** [comment]
```
$gameDir = "h:/Switch Games";    # forward slash! used "internally" by PHP
$contentUrl = "/games";
```
The first is the local path in the filesystem to where your games are and looks correct,
the second is the URL the webserver needs to prefix  to games files so clients can access them (as they can't access them directly via the filesystem, obviously).

You could define an alias `/games` in your webserver config to point to the `H:\Switch Games` directory.
